<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Errores</title>
</head>
<body>

    <h1>Manejo de errores</h1>

    <script>

        try {

            console.log("En el try se agrega el código a evaluar")

            noExiste

            console.log("Segundo mensaje en el Try")
            
        } catch (error) {

            console.log("Catch: captura cualquier error surgido o lanzado en el Try")

            console.log(error)
            
        }finally{

            console.log("Finally: se ejecutará siempre al final de un bloque try catch")

        }

        try {
            let numero = 50
            if (isNaN(numero)) {
                throw new Error("El caracter introducido no es un número")
            }
            console.log(numero * numero)
        } catch (error) {
            console.log("Se produjo el siguiente error: " + error)
        }

    </script>
    
</body>
</html>